# Generated by Django 4.2.3 on 2023-07-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=10, unique=True, verbose_name='URL')),
                ('nsfw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=2000)),
                ('author', models.CharField()),
                ('author_name', models.CharField(default=None, max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=255)),
                ('text', models.CharField(max_length=2000)),
                ('updated_text', models.CharField(default=None, max_length=2000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('author', models.CharField()),
                ('author_name', models.CharField(default=None, max_length=255)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.threadmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('post', models.ForeignKey(blank=True, limit_choices_to={'thread': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.post')),
                ('thread', models.ForeignKey(blank=True, limit_choices_to={'post': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.threadmodel')),
            ],
        ),
    ]
