# Generated by Django 4.2.3 on 2023-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_options_alter_threadmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_text',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='author_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
