# Generated by Django 4.2.3 on 2023-07-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_author_name_alter_post_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', to_field='slug'),
        ),
    ]
